### ISSUE TITLE
我可以在自己的项目里使用代码吗？

### ISSUE THREAD

**Issue by ajjdxns** [Blessing-Studio/minecraft-launch-p#1]
见[AML](https://github.com/ajjdxns-studio/Ajjdxns-Minecraft-Launcher)

**Comment by JustRainy** [comment]
抱歉很久没上github了，今天才看到。可以用，也可以直接pip install。

**Comment by JustRainy** [comment]
对了，记得在项目的Readme里还有启动器里提一嘴就好了

**Comment by ajjdxns** [comment]
谢谢
